[helpers]

[default.variables]
email = "jeremy.damour2@gmail.com"
install_pkgs = true
font = "FiraCode Nerd Font"
# default application
browser = "firefox"
file-manager = "nemo"
pdf-reader = "evince"
terminal = "kitty"

[default.variables.pkgs]

# cargo pkgs
cargo = [
    # replacement of builtin
    "bat",     # replace cat
    "bottom",  # replace top
    "dua-cli", # replace du
    "fd-find", # replace find
    "lsd",     # replace ls
    "mcfly",   # shell-history
    "ripgrep", # replace grep
    "zoxide",  # replace cd

    # other rust application
    "eva", # make calculator

    # dev tool
    "git-delta", # new diff

    # system
    "topgrade",
]

#python package
pip = [
    # replacement of builtin
    "trash-cli", # replace rm with a trash
    "shtab",     # generate shell completion

]

# npm package

[colors.variables]
# Black / grey
color0 = "000000"
color8 = "3f3f3f"

# Red
color1 = "f15252"
color9 = "F50606"

# Green=
color2 = "5ddc7b"
color10 = "09B540"

# Yellow
color3 = "e6e871"
color11 = "f1ef06"

# Blue
color4 = "157ef1"
color12 = "0a54a4"

# Magenta
color5 = "9c37da"
color13 = "640c9b"

# Cyan
color6 = "0fceba"
color14 = "068973"

# white
color7 = "e8e8e8"
color15 = "ffffff"

# cursor
cursor = "7a5Eae"
cursor_text_color = "e0bef3"

[monitors.variables]
laptop = "\"AU Optronics 0xF99A Unknown\""
work_left = "\"Dell Inc. DELL U2412M 0FFXD31U5FEL\""
work_right = "\"Dell Inc. DELL P2723QE 58D3914\""
home_left = "\"Iiyama North America PL2792H 1172001801603\""
home_right = "\"Unknown Unknown Unknown\""

[shell.variables]
editor = "nvim"

# discord
[discord.files]
"discord.json" = "~/.config/discord/settings.json"

# foot (terminal)
[foot]
depends = ["colors"]

[foot.files]
foot = "~/.config/foot/foot.ini"

# kitty (terminal)
[kitty]
depends = ["colors"]

[kitty.files]
"kitty.conf" = "~/.config/kitty/kitty.conf"

# gdb
[gdb.files]
gdbinit = "~/.gdbinit"

#git
[git]
depends = ["shell", "default"]

[git.files]
gitconfig = "~/.gitconfig"

[git.variables]
name = "jeremy.damour"

# glow Markdow viewer
[glow.files]
"glow.yml" = "~/.config/glow/glow.ml"

# kanshi (screen manager)
[kanshi]
depends = ["monitors"]

[kanshi.files]
kanshi = "~/.config/kanshi/"

#neovim (editor)
[neovim.files]
nvim = { target = "~/.config/nvim/", type = "symbolic" }

#starship
[starship.files]
"starship.toml" = "~/.config/starship.toml"

#sway
[sway.files]
"sway" = "~/.config/sway/"

[swaylock.files]
"swaylock.conf" = "~/.config/swaylock/config"

#swaync
[swaync.files]
"swaync.json" = "~/.config/swaync/config.json"

#waybar (sway bar)
[waybar.files]
"waybar" = { target = "~/.config/waybar/", type = "symbolic" }

# tmux
[tmux.files]
"tmux/tmux.conf" = "~/.tmux.conf"
"tmux/tmux-power" = "~/.tmux/plugins/tmux-power"

[tmux.variables]
tmux-power = "~/.tmux/plugins/tmux-power/tmux-power.tmux"

# vscode
[vscode.files]
"vscode_settings.json" = "~/.config/VSCodium/User/settings.json"

#zsh
[zsh]
depends = ["shell"]

[zsh.variables]
config_dir = "$HOME/.config/zsh/config"
script_dir = "$HOME/.config/zsh/script"

[zsh.files]
"zsh/zshrc" = "~/.config/zsh/.zshrc"
"zsh/zshenv" = "~/.zshenv"
"zsh/config" = "~/.config/zsh/config"
"zsh/script" = "~/.config/zsh/script"

[zsh.files."zsh/themes/"]
target = "~/.oh-my-zsh/custom/themes/"
type = "symbolic"

[zsh.files."zsh/plugins/"]
target = "~/.oh-my-zsh/custom/plugins/"
type = "symbolic"
