# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="fino"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# completion enable
autoload -U compinit; compinit

# auto start tmux
[[ -z "$TMUX" ]] && exec tmux
#imports
source {{config_dir}}/variables.zsh
source {{config_dir}}/plugins.zsh
source {{config_dir}}/p10k.zsh
source {{config_dir}}/keybind.zsh
source {{config_dir}}/alias.zsh
source {{config_dir}}/hashdir.zsh
source {{config_dir}}/completion.zsh

# direnv
eval "$(direnv hook zsh)"

# mc fly evaluation
eval "$(mcfly init zsh)"

# source opam
eval "$(opam env)"

# zoxy ide
eval "$(zoxide init zsh)"

