# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="fino"
#ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# completion enable
autoload -U compinit; compinit

# auto start tmux
[[ -z "$TMUX" ]] && exec tmux
#imports
source {{config_dir}}/variables.zsh
source {{config_dir}}/plugins.zsh
source {{config_dir}}/keybind.zsh
source {{config_dir}}/alias.zsh
source {{config_dir}}/hashdir.zsh
source {{config_dir}}/completion.zsh

{{#if (is_executable "direnv")}}
# direnv
eval "$(direnv hook zsh)"
{{/if}}

{{#if (is_executable "opam")}}
# source opam
# This is useful if you're using opam as it adds:
#   - the correct directories to the PATH
#   - auto-completion for the opam binary
# This section can be safely removed at any time if needed.
[[ ! -r "$HOME/.opam/opam-init/init.zsh" ]] || \
  source "$HOME/.opam/opam-init/init.zsh" > \
  /dev/null 2> /dev/null
{{/if}}

{{#if (is_executable "zoxide")}}
# zoxy ide
eval "$(zoxide init zsh)"
{{/if}}

{{#if (is_executable "mcfly")}}
# mc fly evaluation
eval "$(mcfly init zsh)"
{{/if}}

{{#if (is_executable "starship")}}
# sharship theme
eval "$(starship init zsh)"
{{/if}}
